# Form implementation generated from reading ui file 'C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views/dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(411, 218)
        self.Calendar = QtWidgets.QCalendarWidget(dlgCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 411, 221))
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Fecha de alta"))
