# Form implementation generated from reading ui file 'C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views/dlgDeleteServicio.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDeleteServicio(object):
    def setupUi(self, dlgDeleteServicio):
        dlgDeleteServicio.setObjectName("dlgDeleteServicio")
        dlgDeleteServicio.resize(400, 115)
        dlgDeleteServicio.setModal(True)
        self.lblMain = QtWidgets.QLabel(dlgDeleteServicio)
        self.lblMain.setGeometry(QtCore.QRect(20, 20, 371, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.lblMain.setFont(font)
        self.lblMain.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblMain.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        self.lblMain.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblMain.setObjectName("lblMain")
        self.layoutWidget = QtWidgets.QWidget(dlgDeleteServicio)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 60, 231, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnConfirmar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnConfirmar.setMinimumSize(QtCore.QSize(105, 25))
        self.btnConfirmar.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/verified.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnConfirmar.setIcon(icon)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.horizontalLayout.addWidget(self.btnConfirmar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(105, 25))
        self.btnCancelar.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCancelar.setIcon(icon1)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(dlgDeleteServicio)
        QtCore.QMetaObject.connectSlotsByName(dlgDeleteServicio)

    def retranslateUi(self, dlgDeleteServicio):
        _translate = QtCore.QCoreApplication.translate
        dlgDeleteServicio.setWindowTitle(_translate("dlgDeleteServicio", "Confirmación "))
        self.lblMain.setText(_translate("dlgDeleteServicio", "Está apunto de eliminar un servicio. Desea continuar."))
        self.btnConfirmar.setText(_translate("dlgDeleteServicio", "Confirmar"))
        self.btnCancelar.setText(_translate("dlgDeleteServicio", "Cancelar"))
