# Form implementation generated from reading ui file 'C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views/dlgDeleteFactura.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDeleteFactura(object):
    def setupUi(self, dlgDeleteFactura):
        dlgDeleteFactura.setObjectName("dlgDeleteFactura")
        dlgDeleteFactura.resize(400, 210)
        dlgDeleteFactura.setModal(True)
        self.lblMain = QtWidgets.QLabel(dlgDeleteFactura)
        self.lblMain.setGeometry(QtCore.QRect(20, 110, 341, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.lblMain.setFont(font)
        self.lblMain.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblMain.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        self.lblMain.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblMain.setObjectName("lblMain")
        self.layoutWidget = QtWidgets.QWidget(dlgDeleteFactura)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 150, 231, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnConfirmar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnConfirmar.setMinimumSize(QtCore.QSize(105, 25))
        self.btnConfirmar.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/verified.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnConfirmar.setIcon(icon)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.horizontalLayout.addWidget(self.btnConfirmar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(105, 25))
        self.btnCancelar.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCancelar.setIcon(icon1)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.imgAviso = QtWidgets.QLabel(dlgDeleteFactura)
        self.imgAviso.setGeometry(QtCore.QRect(160, 30, 81, 61))
        self.imgAviso.setText("")
        self.imgAviso.setPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/warning.png"))
        self.imgAviso.setScaledContents(True)
        self.imgAviso.setObjectName("imgAviso")

        self.retranslateUi(dlgDeleteFactura)
        QtCore.QMetaObject.connectSlotsByName(dlgDeleteFactura)

    def retranslateUi(self, dlgDeleteFactura):
        _translate = QtCore.QCoreApplication.translate
        dlgDeleteFactura.setWindowTitle(_translate("dlgDeleteFactura", "Confirmación "))
        self.lblMain.setText(_translate("dlgDeleteFactura", "Está apunto de eliminar una factura. ¿Desea continuar?"))
        self.btnConfirmar.setText(_translate("dlgDeleteFactura", "Confirmar"))
        self.btnCancelar.setText(_translate("dlgDeleteFactura", "Cancelar"))
