# Form implementation generated from reading ui file 'C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views/dlgHistorial.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgHistorial(object):
    def setupUi(self, dlgHistorial):
        dlgHistorial.setObjectName("dlgHistorial")
        dlgHistorial.resize(787, 408)
        dlgHistorial.setMinimumSize(QtCore.QSize(787, 408))
        dlgHistorial.setMaximumSize(QtCore.QSize(787, 408))
        dlgHistorial.setModal(False)
        self.tabClientes = QtWidgets.QTableWidget(dlgHistorial)
        self.tabClientes.setEnabled(True)
        self.tabClientes.setGeometry(QtCore.QRect(0, 30, 791, 411))
        self.tabClientes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.tabClientes.setAlternatingRowColors(True)
        self.tabClientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabClientes.setObjectName("tabClientes")
        self.tabClientes.setColumnCount(6)
        self.tabClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(5, item)
        self.tabClientes.horizontalHeader().setCascadingSectionResizes(False)
        self.tabClientes.verticalHeader().setVisible(False)
        self.tabClientes.verticalHeader().setHighlightSections(True)
        self.layoutWidget = QtWidgets.QWidget(dlgHistorial)
        self.layoutWidget.setGeometry(QtCore.QRect(678, 0, 111, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRestaurar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRestaurar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnRestaurar.setMaximumSize(QtCore.QSize(75, 25))
        self.btnRestaurar.setStyleSheet("font: 500 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a21manuellg/Desktop/2DAM/DI/workspace/landingomez/views\\../img/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRestaurar.setIcon(icon)
        self.btnRestaurar.setObjectName("btnRestaurar")
        self.horizontalLayout.addWidget(self.btnRestaurar)
        self.lblTitulo = QtWidgets.QLabel(dlgHistorial)
        self.lblTitulo.setGeometry(QtCore.QRect(0, 0, 681, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("font: 500 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(dlgHistorial)
        QtCore.QMetaObject.connectSlotsByName(dlgHistorial)

    def retranslateUi(self, dlgHistorial):
        _translate = QtCore.QCoreApplication.translate
        dlgHistorial.setWindowTitle(_translate("dlgHistorial", "Histórico de coches"))
        item = self.tabClientes.horizontalHeaderItem(0)
        item.setText(_translate("dlgHistorial", "DNI"))
        item = self.tabClientes.horizontalHeaderItem(1)
        item.setText(_translate("dlgHistorial", "MATRICULA"))
        item = self.tabClientes.horizontalHeaderItem(2)
        item.setText(_translate("dlgHistorial", "MARCA"))
        item = self.tabClientes.horizontalHeaderItem(3)
        item.setText(_translate("dlgHistorial", "MODELO"))
        item = self.tabClientes.horizontalHeaderItem(4)
        item.setText(_translate("dlgHistorial", "MOTOR"))
        item = self.tabClientes.horizontalHeaderItem(5)
        item.setText(_translate("dlgHistorial", "FECHA DE BAJA"))
        self.btnRestaurar.setText(_translate("dlgHistorial", "Restaurar"))
        self.lblTitulo.setText(_translate("dlgHistorial", "COCHES DADOS DE BAJA"))
