from controllers.DlgExitController import DlgExitController
from .DlgCalendarController import DlgCalendarController
from .DlgOpenFileController import DlgOpenFileController
from .DlgIODataController import DlgIODataController
from .DlgHistorialController import DlgHistorialController
from .DlgDeleteClienteController import DlgDeleteClienteController
from .DlgChangeCarOwner import DlgChangeCarOwner
from .DlgDeleteServicioController import DlgDeleteServicioController
from .DlgDeleteFacturaController import DlgDeleteFacturaController
from .DlgAcercaDeController import DlgAcercaDeController

# debe ir de último
from .MainWindowController import MainWindowController
